Rename yml file
elastic/enterprise-search-sharepoint-server-connector pull request #32
Opened 2022-03-07 06:37 UTC by praveen-elastic

Rename config file to "sharepoint_server_connector.yml".

2022-03-07 08:00 UTC, tarekziade requested changes
Looks good. I see one more spot in README.txt

2022-03-07 08:02 UTC, praveen-elastic commented
> Looks good. I see one more spot in README.txt

Hey @tarekziade, I've added that as a part of #31 as all readme changes are added in it.

2022-03-07 08:03 UTC, tarekziade commented
> Looks good. I see one more spot in README.txt

yeah I just saw it, so you can ignore me here :)
Renamings are usually done  in the same patch, that's why I commented

2022-03-07 08:04 UTC, tarekziade approved these changes

2022-03-08 03:20 UTC, serenachou approved these changes

2022-03-08 15:04 UTC, merged